-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Aug 07, 2025 at 01:43 AM
-- Server version: 10.6.22-MariaDB
-- PHP Version: 8.2.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `nikkocal_nixfolio`
--

-- --------------------------------------------------------

--
-- Table structure for table `appointments`
--

CREATE TABLE `appointments` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `phone_number` varchar(20) DEFAULT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `message` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `appointments`
--

INSERT INTO `appointments` (`id`, `name`, `email`, `phone_number`, `subject`, `message`, `created_at`) VALUES
(2, 'z', 'nickocalumpiano@gmail.com', NULL, NULL, 'asd', '2024-11-22 04:39:50'),
(37, 'Mike Jorg Willems\r\n', 'info@professionalseocleanup.com', '', '', 'Hi there, \r\n \r\nWhile checking your nikkocalumpiano.website for its ranks, I have noticed that there are some toxic links pointing towards it. \r\n \r\nGrab your free clean up and improve ranks in no time \r\nhttps://www.professionalseocleanup.com/ \r\n \r\nIt really works, get a free backlinks clean up with us today \r\n \r\nRegards \r\nMike Jorg Willems\r\n \r\nWhatsapp: https://www.professionalseocleanup.com/whatsapp/ \r\nEmail us: info@professionalseocleanup.com', '2025-02-09 06:56:45'),
(38, 'Search Engine', 'submissions@searchindex.site', '3059812608', 'Add nikkocalumpiano.website to Google Search Index!', 'Hello,\r\n\r\nfor your website do be displayed in searches your domain needs to be indexed in the Google Search Index.\r\n\r\nTo add your domain to Google Search Index now, please visit \r\n\r\nhttps://SearchRegister.info/\r\n', '2025-02-09 21:13:02'),
(39, 'Amelia', 'ameliabrown5822@gmail.com', '249351429', 'YouTube Promotion: 700-1600 new subscribers each month', 'Hi there,\r\n\r\nWe run a YouTube growth service, which increases your number of subscribers both safely and practically.\r\n\r\n- We guarantee to gain you 700-1500+ subscribers per month.\r\n- People subscribe because they are interested in your channel/videos, increasing likes, comments and interaction.\r\n- All actions are made manually by our team. We do not use any &#39;bots&#39;.\r\n\r\nThe price is just $60 (USD) per month, and we can start immediately.\r\n\r\nIf you have any questions, let me know, and we can discuss further.\r\n\r\nKind Regards,\r\nAmelia', '2025-02-10 14:39:06'),
(40, 'Mike Richard Bonnet\r\n', 'info@digitalxflow.com', '', '', 'Hi there, \r\n \r\nLooking to improve your website&#39;s local rankings? We offer Country Targeted Backlinks to help you dominate your niche. With backlinks from high-quality, local domains, your website will see increased relevance, traffic, and authority in your chosen region. \r\n \r\nCheck out our service here: \r\nhttps://www.digitalxflow.com/country-backlinks/ \r\nOr chat with us on WhatsApp: https://www.digitalxflow.com/whatsapp-us/ \r\n \r\n \r\nBest regards, \r\nMike Richard Bonnet\r\n \r\nDgital X Flow Team', '2025-02-10 19:42:11'),
(41, 'Waheed Algore', 'intl.law7@aol.com', '', '', 'Dear Sir/Madam, \r\n \r\nSecuring funding is a significant challenge for startups and established businesses. Our company specializes in customized financing solutions for both startups and existing enterprises. \r\n \r\nWe offer two flexible options: \r\n \r\n1. Debt financing with a competitive 3% annual interest rate and no early repayment penalties. \r\n2. Venture capital funding in exchange for a modest 10% equity stake, allowing you to access essential resources while retaining control. \r\n \r\nWe understand the unique challenges businesses face and are committed to providing tailored financing solutions. \r\n \r\nFor further details about our funding scheme, please contact me directly at Email waheed@cateusgroup.org \r\n \r\nBest regards, \r\nWaheed Algore \r\nLead Investment Team \r\nEmail waheed@cateusgroup.org', '2025-02-11 22:19:51'),
(42, 'Yasuhiro Yamada', 'rohtopharmaceutical@via.tokyo.jp', '', '', 'Greetings, Mr./Ms. \n \nWith all due respect. We are looking for a Spokesperson/Financial Coordinator for ROHTO Pharmaceutical Co., Ltd. based in the USA, Canada, or Europe. This part-time role offers a minimum $5k salary and requires only a few minutes of your time daily. It will not create any conflicts if you work with other companies. If interested, please contact apply@rohtopharmaceutical.com \n \nBest regards, \nYasuhiro Yamada \nSenior Executive Officer \nhttps://rohtopharmaceutical.com/', '2025-02-13 04:05:55'),
(43, 'Joanna', 'joannariggs94@gmail.com', '7786969864', 'Video Promotion for nikkocalumpiano.website?', 'Hi,\r\n\r\nI just visited nikkocalumpiano.website and wondered if you&#39;d ever thought about having an engaging video to explain what you do?\r\n\r\nOur videos cost just $195 for a 30 second video ($239 for 60 seconds) and include a full script, voice-over and video.\r\n\r\nI can show you some previous videos we&#39;ve done if you want me to send some over. Let me know if you&#39;re interested in seeing samples of our previous work.\r\n\r\nRegards,\r\nJoanna', '2025-02-15 13:39:24'),
(44, 'Search Engine', 'angelina.ha@yahoo.com', '7968708105', 'Add nikkocalumpiano.website to Google Search Index!', 'Hello,\r\n\r\nfor your website do be displayed in searches your domain needs to be indexed in the Google Search Index.\r\n\r\nTo add your domain to Google Search Index now, please visit \r\n\r\nhttps://SearchRegister.net', '2025-02-19 19:34:19'),
(45, 'Mike Jesse Fischer\r\n', 'info@strictlydigital.net', '', '', 'Hello, \r\n \r\nGetting some bunch of links pointing to nikkocalumpiano.website could have zero worth or harmful results for your site. \r\n \r\nIt really makes no difference the total inbound links you have, what matters is the number of ranking terms those websites appear in search for. \r\n \r\nThat is the key element. \r\nNot the overrated third-party metrics or Domain Rating. \r\nAnyone can manipulate those. \r\nBUT the number of ranking keywords the domains that send backlinks to you rank for. \r\nThatâ€™s it. \r\n \r\nGet these quality links redirect to your site and your site will see real growth! \r\n \r\nWe are offering this exclusive service here: \r\nhttps://www.strictlydigital.net/product/semrush-backlinks/ \r\n \r\nNeed more details, or want clarification, reach out here: \r\nhttps://www.strictlydigital.net/whatsapp-us/ \r\n \r\nSincerely, \r\nMike Jesse Fischer\r\n \r\nstrictlydigital.net \r\nPhone/WhatsApp: +1 (877) 566-3738', '2025-02-21 23:43:36'),
(46, 'Mike Karl Janssen\r\n', 'mike@monkeydigital.co', '', '', 'Hello, \r\n \r\nThis is Mike from Monkey Digital, \r\nI am getting in touch to discuss a exciting collaboration. \r\n \r\nHow would you like to place our ads on your site and connect via your unique referral link towards high-demand services from our business? \r\n \r\nThis way, you earn a recurring 35% residual income, month after month from any sales that generate from your site. \r\n \r\nThink about it, most website owners require SEO, so this is a huge opportunity. \r\n \r\nWe already have thousands of affiliates and our commissions are processed every month. \r\nIn the past month, we paid out a significant amount in affiliate earnings to our partners. \r\n \r\nIf you want in, kindly chat with us here: \r\nhttps://monkeydigital.co/affiliates-whatsapp/ \r\n \r\nOr register today: \r\nhttps://www.monkeydigital.co/join-our-affiliate-program/ \r\n \r\nCheers, \r\nMike Karl Janssen\r\n \r\nPhone/whatsapp: +1 (775) 314-7914', '2025-02-22 06:45:13'),
(47, 'Alex Amin', 'projectuganda256@gmail.com', '', '', 'Greetings, \r\n \r\nI hope this message finds you well. We are seeking strategic business partners and individuals interested in collaborating on exclusive investment opportunities. We represent a network of high-net-worth individuals (HNWIs) from Ukraine, Russia, Africa and the Middle East \r\n \r\nGiven the nature of the funds, further details will be shared upon request including amount involved. If it interests you to collaborate with us at no risk, please feel free to reach out for a confidential discussion. \r\n \r\nLooking forward to your response. \r\n \r\nBest regards, \r\n \r\nAlex Amin \r\nEmail: abcgconsult@gmail.com', '2025-02-28 18:51:12'),
(48, 'Search Engine', 'markus.krawczyk@msn.com', '7021779546', 'Add nikkocalumpiano.website to Google Search Index!', 'Hello,\r\n\r\nfor your website do be displayed in searches your domain needs to be indexed in the Google Search Index.\r\n\r\nTo add your domain to Google Search Index now, please visit \r\n\r\nhttps://SearchRegister.net', '2025-03-02 00:10:36'),
(49, 'Search Engine', 'submissions@searchindex.site', '108208079', 'Add nikkocalumpiano.website to Google Search Index!', 'Hello,\r\n\r\nfor your website do be displayed in searches your domain needs to be indexed in the Google Search Index.\r\n\r\nTo add your domain to Google Search Index now, please visit \r\n\r\nhttps://SearchRegister.info/\r\n', '2025-03-11 20:25:24'),
(50, 'Nikko Calumpiano', 'nickocalumpiano@gmail.com', '09458279256', 'Hyop kq', 'Potangina mo gagu', '2025-03-12 05:51:19'),
(51, 'Nikko Calumpiano', 'nickocalumpiano@gmail.com', '', '', 'pakyubitch', '2025-03-12 05:51:52'),
(52, 'Joanna', 'joannariggs94@gmail.com', '2036417160', 'Video Promotion for your website?', 'Hi,\r\n\r\nI just visited nikkocalumpiano.website and wondered if you&#39;d ever thought about having an engaging video to explain what you do?\r\n\r\nOur prices start from just $195.\r\n\r\nLet me know if you&#39;re interested in seeing samples of our previous work.\r\n\r\nRegards,\r\nJoanna\r\n\r\nUnsubscribe: https://removeme.live/unsubscribe.php?d=nikkocalumpiano.website', '2025-03-15 15:12:14'),
(53, 'Search Engine', 'tiffany.louie@yahoo.com', '48815983', 'Add nikkocalumpiano.website to Google Search Index!', 'Hello,\r\n\r\nfor your website do be displayed in searches your domain needs to be indexed in the Google Search Index.\r\n\r\nTo add your domain to Google Search Index now, please visit \r\n\r\nhttps://SearchRegister.net', '2025-03-21 19:15:11'),
(54, 'Ferne', 'gaunson.ferne@googlemail.com', '623998103', 'To the nikkocalumpiano.website Admin. You&#39;re Losing Google Traffic (Here&#39;s a Free Fix)', 'Hi,\r\n\r\nI came across your website and noticed that many of your articles arenâ€™t fully optimized for SEO. That means youâ€™re likely missing out on valuable search traffic even though youâ€™ve already spent time and effort creating content.\r\n\r\nIâ€™m not selling SEO services. But I do want to help.\r\n\r\nThere&#39;s an AI tool that helps optimize blog content for SEO saving hours of manual work while improving rankings.. Itâ€™s called SEOwriting.ai, and right now, you can claim 25,000 words for free (only through this link).\r\n\r\ní ½í±‰ https://seowriting.ai?fp_ref=boostrevenue\r\n\r\nWhy wait? Every day your content isn&#39;t optimized is another day youâ€™re losing traffic to competitors.\r\n\r\nLet me know if you try it.  happy to help with tips!\r\n\r\nBest,\r\nGordon Salo', '2025-03-28 22:47:04'),
(55, 'Sallie', 'nona.sallie@googlemail.com', '3548209082', 'Exclusive Offer: All-in-One Uncensored AI Platform', 'Hi,\r\n\r\nAre you tired of paying multiple monthly subscriptions for premium AI tools? \r\n\r\nI&#39;d like to introduce the world&#39;s first cloud-based platform that gives you access to premium uncensored versions of leading AI apps in a single dashboard:\r\n\r\nDeepSeek R1, Grok, ChatGPT-4o, Gemini 2.0 Flash, Claude Pro, and more.\r\nNo monthly fees - just a one-time payment of $14.95 (normally $97).\r\nFull commercial license included.\r\nLaunch your own AI subscription platform and charge any amount\r\n\r\nKey Features:\r\n\r\nUncensored AI chat with no restrictions on topics.\r\nSupport for 40+ languages.\r\nCode generation capabilities.\r\nEasy-to-use dashboard.\r\n30-day money-back guarantee\r\n\r\nThis limited-time offer includes all premium AI tools without any censorship or monthly fees. You&#39;ll have everything you need to create high-quality content, generate stunning visuals, write code, and more.\r\n\r\nLearn more: https://furtherinfo.info/oneai\r\n\r\nBest regards,\r\nSallie', '2025-03-31 04:05:44'),
(56, 'MyName', 'egsiwjsl@form-check.online', 'John', 'Hello', 'hfpldTs DQZaNtks IpBrCWT SCLSh hXMVsbj BRYQXau', '2025-03-31 19:09:53'),
(57, 'MyName', 'gxpwomil@form-check.online', '', '', 'lbE gmvpXGEF kGkABZrF UuMZ LRGUVaca rRRLy', '2025-03-31 19:09:53'),
(58, 'Search Engine', 'dakota.hibbins@hotmail.com', '4523302', 'Add nikkocalumpiano.website to Google Search Index!', 'Hello,\n\nfor your website do be displayed in searches your domain needs to be indexed in the Google Search Index.\n\nTo add your domain to Google Search Index now, please visit \n\nhttps://SearchRegister.net', '2025-03-31 21:45:38'),
(59, 'Leonore', 'funk.leonore@gmail.com', '7810352532', 'Build Your Own AI Subscription Business: All Premium Tools Included', 'Hi,\r\n\r\nAre you tired of paying multiple monthly subscriptions for premium AI tools? \r\n\r\nI&#39;d like to introduce the world&#39;s first cloud-based platform that gives you access to premium uncensored versions of leading AI apps in a single dashboard:\r\n\r\nDeepSeek R1, Grok, ChatGPT-4o, Gemini 2.0 Flash, Claude Pro, and more.\r\nNo monthly fees - just a one-time payment of $14.95 (normally $97).\r\nFull commercial license included.\r\nLaunch your own AI subscription platform and charge any amount\r\n\r\nKey Features:\r\n\r\nUncensored AI chat with no restrictions on topics.\r\nSupport for 40+ languages.\r\nCode generation capabilities.\r\nEasy-to-use dashboard.\r\n30-day money-back guarantee\r\n\r\nThis limited-time offer includes all premium AI tools without any censorship or monthly fees. You&#39;ll have everything you need to create high-quality content, generate stunning visuals, write code, and more.\r\n\r\nLearn more: https://furtherinfo.info/oneai\r\n\r\nBest regards,\r\nLeonore\r\n\r\nIf you do not wish us to contact you again, let us know here: https://removeme.live/a/unsubscribe.php?d=nikkocalumpiano.website', '2025-04-02 21:59:49'),
(60, 'Mike Levi Morel\r\n', 'info@digital-x-press.com', '', '', 'Hello, \n \nI understand that many have difficulty to grasp that SEO is a long-term game and a methodical ongoing investment. \n \nUnfortunately, very few webmasters have the patience to witness the gradual yet business-changing trends that can elevate their business. \n \nWith constant search engine updates, a steady, long-term strategy is essential for getting a sustainable profit. \n \nIf you agree this as the best method, give us a try! \n \nDiscover Our Monthly SEO Services \nhttps://www.digital-x-press.com/unbeatable-seo/ \n \nContact Us on Instant Messaging \nhttps://www.digital-x-press.com/whatsapp-us/ \n \nWe provide exceptional value for your investment, and you wonâ€™t regret choosing us as your digital agency. \n \nBest regards, \nDigital X SEO Experts \nPhone/WhatsApp: +1 (844) 754-1148', '2025-04-07 20:52:12'),
(61, 'Katelyn', 'katelynraiden@gmail.com', '247859766', 'Youtube Promotion: Grow your subscribers by 700 each month', 'Hi there,\r\n\r\nWe run a Youtube growth service, where we can increase your subscriber count safely and practically. \r\n\r\n- Guaranteed: We guarantee to gain you 700-1500 new subscribers each month.\r\n- Real, human subscribers who subscribe because they are interested in your channel/videos.\r\n- Safe: All actions are done, without using any automated tasks / bots.\r\n\r\nOur price is just $60 (USD) per month and we can start immediately.\r\n\r\nIf you are interested then we can discuss further.\r\n\r\nKind Regards,\r\nKatelyn', '2025-04-09 12:36:09'),
(62, 'Search Engine', 'hateley.michale@googlemail.com', '883066399', 'Add nikkocalumpiano.website to Google Search Index!', 'Hello,\r\n\r\nfor your website do be displayed in searches your domain needs to be indexed in the Google Search Index.\r\n\r\nTo add your domain to Google Search Index now, please visit \r\n\r\nhttps://SearchRegister.net', '2025-04-10 22:35:58'),
(63, 'Ashly', 'apodaca.ashly@gmail.com', '2474797896', 'Drive AI Traffic to nikkocalumpiano.website - No Ads Needed', 'Hi there,\r\n\r\nWe wanted to introduce you to a revolutionary system that helps you create AI-powered tools to generate steady, qualified leads without paid advertising.\r\n\r\nKey benefits:\r\n\r\nCreate AI tools in minutes with simple copy/paste templates \r\nDrive free, targeted traffic to any niche or offer  \r\nBuilt-in call-to-action system to funnel leads to your sales pages \r\nNo coding or technical experience needed\r\n\r\nWe&#39;re currently offering a special launch price of $17 (regular $97) which includes bonus training on traffic generation and AI monetization.\r\n\r\nFor more details, check out: https://furtherinfo.info/etb\r\n\r\nThanks,\r\nAshly', '2025-04-12 20:59:38'),
(64, 'Nikko', 'nickocalumpiano@gmail.com', '', '', 'Test', '2025-04-14 02:18:20'),
(65, 'Test', 'itsupport@pcis.edu.ph', '09319914266', 'Tst', 'panot tangina mo ggaug', '2025-04-19 05:07:25'),
(66, 'Test', 'itsupport@pcis.edu.ph', '09319914266', 'Tst', 'panot tangina mo ggaug', '2025-04-19 05:07:26'),
(67, 'Test', 'itsupport@pcis.edu.ph', '', '', 'sabado', '2025-04-19 05:07:59'),
(68, 'Joanna', 'joannariggs278@gmail.com', '2506913445', 'Explainer Video for your website?', 'Hi,\n\nI just visited nikkocalumpiano.website and wondered if you&#39;d ever thought about having an engaging video to explain what you do?\n\nOur videos cost just $195 for a 30 second video ($239 for 60 seconds) and include a full script, voice-over and video.\n\nI can show you some previous videos we&#39;ve done if you want me to send some over. Let me know if you&#39;re interested in seeing samples of our previous work.\n\nRegards,\nJoanna', '2025-04-20 23:42:01'),
(69, 'NAEWTRER1591090NEHTYHYHTR', 'lnxlrrhc@bonsoirmail.com', '', '', 'METRYTRH1591090MAERWETT', '2025-04-21 21:50:11'),
(70, 'Mike Charles Maes\r\n', 'mike@monkeydigital.co', '', '', 'Hi there, \n \nI wanted to connect with something that could seriously improve your websiteâ€™s traffic. We work with a trusted ad network that allows us to deliver authentic, location-based social ads traffic for just $10 per 10,000 visits. \n \nThis isn&#39;t junk clicksâ€”itâ€™s engaged traffic, tailored to your target country and niche. \n \nWhat you get: \n \n10,000+ genuine visitors for just $10 \nLocalized traffic for multiple regions \nHigher volumes available based on your needs \nTrusted by SEO expertsâ€”we even use this for our SEO clients! \n \nWant to give it a try? Check out the details here: \nhttps://www.monkeydigital.co/product/country-targeted-traffic/ \n \nOr chat with us on WhatsApp: \nhttps://monkeydigital.co/whatsapp-us/ \n \nLooking forward to working with you! \n \nBest, \nMike Charles Maes\n \nPhone/whatsapp: +1 (775) 314-7914', '2025-04-23 09:34:07'),
(71, 'Mac', 'info@fierro.easerelief.net', '626818589', 'Mac Fierro', 'EASE YOUR PAIN IN 10 MINUTES EFFORTLESSLY\r\n\r\nBe Free from sore muscles and joint pain\r\nTry FitRx Wireless Massager & Relieve YOUR Pain Effortlessly In 10 Min!\r\nSave 50% OFF + FREE Priority Shipping\r\n\r\nShop Now: https://EaseRelief.net\r\n\r\nThanks and Best Regards, \r\n\r\nMac', '2025-05-25 00:59:43'),
(72, 'Karol', 'info@gentle.bangeshop.com', '5139365445', 'Nixfolio - Nikko E. Calumpiano', 'Good Morning, \n\nI hope this email finds you well. I wanted to let you know about our new BANGE backpacks and sling bags that just released.\n\nBange is perfect for students, professionals and travelers. The backpacks and sling bags feature a built-in USB charging port, making it easy to charge your devices on the go.  Also they are waterproof and anti-theft design, making it ideal for carrying your valuables.\n\nBoth bags are made of durable and high-quality materials, and are perfect for everyday use or travel.\n\nOrder yours now at 50% OFF with FREE Shipping: http://bangeshop.com\n\nTo your success,\n\nKarol', '2025-06-10 05:41:43'),
(73, 'Rodolfo', 'rodolfo.gallop@outlook.com', '887409437', 'One Platform, Every Top AI Modelâ€”No Monthly Fees, No Hassle!', 'Access ChatGPT, Claude, Gemini Pro , Kling AI, LLaMA, Mistral, DALL.E, LLaMa & moreâ€”all from a single dashboard.\r\n\r\nNo subscriptions or no monthly feesâ€”pay once and enjoy lifetime access.\r\n\r\nAutomatically switch between AI models based on task requirements.\r\n\r\nAnd much more ... www.novaai.expert/AI-IntelliKit', '2025-06-16 13:02:52'),
(74, 'Quincy', 'info@beauregard.medicopostura.com', '3696526409', 'Quincy Beauregard', 'Hey there \n\nLooking to improve your posture and live a healthier life? Our Medico Posturaâ„¢ Body Posture Corrector is here to help!\n\nExperience instant posture improvement with Medico Posturaâ„¢. This easy-to-use device can be worn anywhere, anytime â€“ at home, work, or even while you sleep.\n\nMade from lightweight, breathable fabric, it ensures comfort all day long.\n\nGrab it today at a fantastic 60% OFF: https://medicopostura.com\n\nPlus, enjoy FREE shipping for today only!\n\nDon&#39;t miss out on this amazing deal. Get yours now and start transforming your posture!\n\nBest Wishes, \n\nQuincy', '2025-06-18 20:09:53'),
(75, 'Sheila', 'info@nikkocalumpiano.website', '251928265', 'Sheila Von Stieglitz', 'PawSaferâ„¢ Can Safely Trim Your Dog&#39;S Nails In No Time From Home.\n\nGet it while it&#39;s still 50% OFF + FREE Shipping\n\nBuy here: https://pawtrim.shop\n \nSincerely, \n \nSheila', '2025-06-24 08:13:44'),
(76, 'Hannelore', 'info@nikkocalumpiano.website', '487891279', 'Nixfolio - Nikko E. Calumpiano', 'Good Morning \r\n\r\nI wanted to reach out and let you know about our new dog harness. It&#39;s really easy to put on and take off - in just 2 seconds - and it&#39;s personalized for each dog. \r\nPlus, we offer a lifetime warranty so you can be sure your pet is always safe and stylish.\r\n\r\nWe&#39;ve had a lot of success with it so far and I think your dog would love it. \r\n\r\nGet yours today with 50% OFF: https://caredogbest.com\r\n\r\nFREE Shipping - TODAY ONLY! \r\n\r\nBest Wishes, \r\n\r\nHannelore', '2025-07-02 02:15:56'),
(77, 'Yong', 'yong.goodell@gmail.com', '341993674', 'Launch-Ready Sales Funnels with Instant Access to Pre-Approved Products', 'You Donâ€™t Need Tech Skills To Succeed. Just a Funnel That Handles the Heavy Lifting For You Ready to Go in Minutes From Now\r\nLaunch Your Own Funnel Featuring Share-Worthy AI Tools Built to Spark Engagement\r\nBuilt-In Tools Help You Get Traffic + Preloaded Emails Feature Your Affiliate Links\r\nNo Ads. No Writing. No Tech Skills Needed â€“ Just Follow a Few Simple Steps\r\nEMAILS, GIVEAWAYS & BUILT-IN TRAFFIC TOOLS\r\n\r\nmore ... https://www.novaai.expert/WarriorFunnels', '2025-07-02 10:10:19'),
(78, 'Jerald', 'jerald-price@msn.com', '3621369035', 'Jerald Price', 'Hi\r\n\r\nCraving crispy, delicious meals without the guilt? Our Beautifulâ„¢ Air Fryer makes healthy cooking a breeze!\r\n\r\nItâ€™s simple to use and perfect for quick, tasty meals at home.\r\n\r\nGrab yours today at an exclusive 30% OFF: https://beautiful.tidbuy.com\r\n\r\nPlus, FREE Priority Shipping â€“ today only!\r\n\r\nDonâ€™t miss out â€“ order now and elevate your cooking game!\r\n\r\nEnjoy, \r\n\r\nJerald', '2025-07-15 17:45:51');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `appointments`
--
ALTER TABLE `appointments`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `appointments`
--
ALTER TABLE `appointments`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=79;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
